# Generated by Django 3.2.4 on 2021-08-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Client_Fund',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Clients_Brokerage',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Create_Clients',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='View_Client',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dashboard',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=150),
        ),
    ]
