# Generated by Django 3.2.4 on 2021-09-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210831_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='watchlists',
            field=models.TextField(default=' ', max_length=150),
        ),
    ]
