# Generated by Django 3.2.4 on 2021-09-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_watchlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='watchlists',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
    ]
